### ISSUE TITLE
大佬你好，这个模型用了多少粤语数据集来训练的？

### ISSUE THREAD

**Issue by JustinhoCHN** [kirbystudy/vits-cantonese#1]
我想为我今年过世的亲人克隆他的声音，想合成他的声音说一段话，“骗”一下老人家他还在生。
这个模型用了多少粤语数据集来训练的？您的测试效果如何？

**Comment by kirbystudy** [comment]
用了3个不同的女声线，数据集2000多条训练的，效果我感觉还可以。
